//! Groth16 proof verifier for the BN254 (alt_bn128) curve.
//!
//! Implements the Groth16 verification equation:
//!   e(A, B) = e(α, β) · e(vk_x, γ) · e(C, δ)
//!
//! Rearranged for efficient multi-pairing:
//!   e(A, B) · e(-α, β) · e(-vk_x, γ) · e(-C, δ) = 1
//!
//! The verification key is generated by the trusted setup ceremony
//! and stored in `vk_constants.rs` (auto-generated by scripts/export_vk_rust.js).
//!
//! See plan.md Sections 4.5 and 4.6.

use ark_bn254::{Bn254, Fq, Fq2, Fr, G1Affine, G1Projective, G2Affine};
use ark_ec::{pairing::Pairing, CurveGroup};
use ark_ff::{PrimeField, Zero};

/// Number of public inputs in the withdrawal circuit.
/// Public inputs: root, nullifierHash, recipient, relayer, fee
pub const NUM_PUBLIC_INPUTS: usize = 5;

/// G1 point encoded as two 32-byte big-endian coordinates.
pub struct G1Point {
    pub x: [u8; 32],
    pub y: [u8; 32],
}

/// G2 point encoded as four 32-byte big-endian coordinates.
/// G2 is over Fq2 = Fq[u]/(u² + 1), with real (c0) and imaginary (c1) parts.
pub struct G2Point {
    pub x_c0: [u8; 32],
    pub x_c1: [u8; 32],
    pub y_c0: [u8; 32],
    pub y_c1: [u8; 32],
}

/// Groth16 verification key (populated from trusted setup constants).
pub struct VerifyingKey {
    pub alpha_g1: G1Point,
    pub beta_g2: G2Point,
    pub gamma_g2: G2Point,
    pub delta_g2: G2Point,
    pub ic: [G1Point; NUM_PUBLIC_INPUTS + 1],
}

// ── Point deserialization ──

/// Deserialize a big-endian 32-byte array to an Fq element.
fn bytes_to_fq(bytes: &[u8; 32]) -> Fq {
    let mut le = *bytes;
    le.reverse();
    Fq::from_le_bytes_mod_order(&le)
}

/// Deserialize and validate a G1 affine point.
fn decode_g1(point: &G1Point) -> Option<G1Affine> {
    let x = bytes_to_fq(&point.x);
    let y = bytes_to_fq(&point.y);
    let affine = G1Affine::new_unchecked(x, y);
    if affine.is_on_curve() && affine.is_in_correct_subgroup_assuming_on_curve() {
        Some(affine)
    } else {
        None
    }
}

/// Deserialize and validate a G2 affine point.
fn decode_g2(point: &G2Point) -> Option<G2Affine> {
    let x = Fq2::new(bytes_to_fq(&point.x_c0), bytes_to_fq(&point.x_c1));
    let y = Fq2::new(bytes_to_fq(&point.y_c0), bytes_to_fq(&point.y_c1));
    let affine = G2Affine::new_unchecked(x, y);
    if affine.is_on_curve() && affine.is_in_correct_subgroup_assuming_on_curve() {
        Some(affine)
    } else {
        None
    }
}

/// Deserialize a Groth16 proof from 256 raw bytes.
///
/// Layout (big-endian, uncompressed affine points):
///   [0..64)    — A (G1): x[32] || y[32]
///   [64..192)  — B (G2): x_c0[32] || x_c1[32] || y_c0[32] || y_c1[32]
///   [192..256) — C (G1): x[32] || y[32]
///
/// Returns None if any point is invalid (not on curve or wrong subgroup).
fn decode_proof(bytes: &[u8; 256]) -> Option<(G1Affine, G2Affine, G1Affine)> {
    let a = decode_g1(&G1Point {
        x: bytes[0..32].try_into().ok()?,
        y: bytes[32..64].try_into().ok()?,
    })?;

    let b = decode_g2(&G2Point {
        x_c0: bytes[64..96].try_into().ok()?,
        x_c1: bytes[96..128].try_into().ok()?,
        y_c0: bytes[128..160].try_into().ok()?,
        y_c1: bytes[160..192].try_into().ok()?,
    })?;

    let c = decode_g1(&G1Point {
        x: bytes[192..224].try_into().ok()?,
        y: bytes[224..256].try_into().ok()?,
    })?;

    Some((a, b, c))
}

// ── Verification key loading ──

/// Decoded verification key with arkworks native types.
struct DecodedVK {
    alpha_g1: G1Affine,
    beta_g2: G2Affine,
    gamma_g2: G2Affine,
    delta_g2: G2Affine,
    ic: [G1Affine; NUM_PUBLIC_INPUTS + 1],
}

/// Load and decode the verification key from compiled constants.
///
/// The `vk` feature gate controls whether the verification key is available.
/// When disabled (before trusted setup), all verification attempts fail gracefully.
fn load_verification_key() -> Option<DecodedVK> {
    #[cfg(feature = "vk")]
    {
        use crate::vk_constants;
        let raw = vk_constants::verification_key();

        let alpha_g1 = decode_g1(&raw.alpha_g1)?;
        let beta_g2 = decode_g2(&raw.beta_g2)?;
        let gamma_g2 = decode_g2(&raw.gamma_g2)?;
        let delta_g2 = decode_g2(&raw.delta_g2)?;

        let mut ic = [G1Affine::identity(); NUM_PUBLIC_INPUTS + 1];
        for (i, point) in raw.ic.iter().enumerate() {
            ic[i] = decode_g1(point)?;
        }

        Some(DecodedVK {
            alpha_g1,
            beta_g2,
            gamma_g2,
            delta_g2,
            ic,
        })
    }

    #[cfg(not(feature = "vk"))]
    None
}

// ── Public API ──

/// Verify a Groth16 proof against the hardcoded verification key.
///
/// # Arguments
/// * `proof_bytes` — 256-byte encoded proof (A || B || C)
/// * `public_inputs` — 5 public input field elements as big-endian 32-byte arrays
///
/// # Returns
/// `true` if the proof is valid, `false` otherwise.
///
/// # Security
/// - All curve points are validated (on-curve + correct subgroup)
/// - Public inputs are reduced modulo the scalar field order
/// - Uses multi-pairing for efficient verification
pub fn verify_proof(
    proof_bytes: &[u8; 256],
    public_inputs: &[[u8; 32]; NUM_PUBLIC_INPUTS],
) -> bool {
    // 1. Decode proof (validates curve points)
    let (a, b, c) = match decode_proof(proof_bytes) {
        Some(p) => p,
        None => return false,
    };

    // 2. Load verification key
    let vk = match load_verification_key() {
        Some(vk) => vk,
        None => return false,
    };

    // 3. Convert public inputs to scalar field elements
    let mut fr_inputs = [Fr::from(0u64); NUM_PUBLIC_INPUTS];
    for (i, input_bytes) in public_inputs.iter().enumerate() {
        let mut le = *input_bytes;
        le.reverse();
        fr_inputs[i] = Fr::from_le_bytes_mod_order(&le);
    }

    // 4. Compute vk_x = IC[0] + Σ(public_inputs[i] · IC[i+1])
    let mut vk_x: G1Projective = vk.ic[0].into();
    for i in 0..NUM_PUBLIC_INPUTS {
        vk_x += vk.ic[i + 1] * fr_inputs[i];
    }
    let vk_x_affine = vk_x.into_affine();

    // 5. Multi-pairing verification:
    //    e(A, B) · e(-α, β) · e(-vk_x, γ) · e(-C, δ) == identity
    //
    //    This is equivalent to checking:
    //    e(A, B) == e(α, β) · e(vk_x, γ) · e(C, δ)
    //
    //    but computed in a single multi-pairing for efficiency.
    let result = Bn254::multi_pairing(
        [a, -vk.alpha_g1, -vk_x_affine, -c],
        [b, vk.beta_g2, vk.gamma_g2, vk.delta_g2],
    );

    result.is_zero()
}
