#!/usr/bin/env node
/**
 * Private Stellar Protocol — Verification Key Export
 *
 * Converts a snarkjs verification_key.json into Rust constants
 * for the Groth16 verifier in the MixerPool contract.
 *
 * Usage: node scripts/export_vk_rust.js [path/to/verification_key.json]
 *
 * Output: contracts/mixer_pool/src/vk_constants.rs
 */

const fs = require("fs");
const path = require("path");

const vkPath =
  process.argv[2] || path.join("circuits", "build", "verification_key.json");
const outputPath = path.join(
  "contracts",
  "mixer_pool",
  "src",
  "vk_constants.rs"
);

if (!fs.existsSync(vkPath)) {
  console.error(`Verification key not found at: ${vkPath}`);
  console.error("Run the trusted setup first: npm run setup");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

/**
 * Convert a decimal string to a 32-byte big-endian hex array.
 * Field elements in snarkjs are decimal strings representing
 * integers in the BN128 scalar field.
 */
function decToBytes32(decStr) {
  let n = BigInt(decStr);
  const bytes = [];
  for (let i = 0; i < 32; i++) {
    bytes.unshift(Number(n & 0xffn));
    n >>= 8n;
  }
  return bytes;
}

function formatBytes(bytes) {
  return bytes.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
}

/**
 * Format a G1 point [x, y, "1"] as Rust byte arrays.
 * snarkjs G1 points are [x, y, z] in projective coordinates,
 * but the verification key uses affine (z=1).
 */
function formatG1(point) {
  const x = decToBytes32(point[0]);
  const y = decToBytes32(point[1]);
  return `G1Point {
        x: [${formatBytes(x)}],
        y: [${formatBytes(y)}],
    }`;
}

/**
 * Format a G2 point [[x1, x0], [y1, y0], ["1","0"]] as Rust byte arrays.
 * G2 points are over the extension field Fq2 = Fq[u]/(u^2 + 1).
 * snarkjs stores Fq2 elements as [c1, c0] (imaginary, real).
 */
function formatG2(point) {
  const x0 = decToBytes32(point[0][1]); // real part of x
  const x1 = decToBytes32(point[0][0]); // imaginary part of x
  const y0 = decToBytes32(point[1][1]); // real part of y
  const y1 = decToBytes32(point[1][0]); // imaginary part of y
  return `G2Point {
        x_c0: [${formatBytes(x0)}],
        x_c1: [${formatBytes(x1)}],
        y_c0: [${formatBytes(y0)}],
        y_c1: [${formatBytes(y1)}],
    }`;
}

// Build the Rust source
let rust = `// Auto-generated by scripts/export_vk_rust.js
// DO NOT EDIT — regenerate by running: node scripts/export_vk_rust.js
//
// This file contains the Groth16 verification key constants for the
// withdrawal circuit. These constants are circuit-specific and tied
// to the trusted setup ceremony.

use crate::verifier::{G1Point, G2Point, VerifyingKey};

/// Number of public inputs in the withdrawal circuit.
/// Public inputs: root, nullifierHash, recipient, relayer, fee
pub const NUM_PUBLIC_INPUTS: usize = ${vk.IC.length - 1};

pub fn verification_key() -> VerifyingKey {
    VerifyingKey {
        alpha_g1: ${formatG1(vk.vk_alpha_1)},
        beta_g2: ${formatG2(vk.vk_beta_2)},
        gamma_g2: ${formatG2(vk.vk_gamma_2)},
        delta_g2: ${formatG2(vk.vk_delta_2)},
        ic: [
`;

for (let i = 0; i < vk.IC.length; i++) {
  rust += `            ${formatG1(vk.IC[i])},\n`;
}

rust += `        ],
    }
}
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, rust);
console.log(`Verification key exported to: ${outputPath}`);
console.log(`  Public inputs: ${vk.IC.length - 1}`);
console.log(`  IC points: ${vk.IC.length}`);
